### PR TITLE
hotfix: add husky and fix warnings on the ui

### LINKED ISSUE #961: Warning Errors on GUI
### Describe the bug

There are some warning errors on the GUI of our React app. These warning messages are affecting the behavior of the GUI elements.

### Steps to reproduce

1. Run our GUI.
2. Open the web browser and navigate to the app.
3. Open the browser's developer console.
4. Interact with each component of the GUI (e.g., click buttons, enter data, navigate through screens).
5. Monitor the console for warning messages during the interaction.

### Affected services

UI

### Broker version

v1.0.2

### Platforms

_No response_

### If UI - Browsers

_No response_

### Environment

Development

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by rolwin100**
added husky as pre-commit hook
fixed warnings on the UI still few are pending

resolves #961

### CODE REVIEW

**Comment by rolwin100** [comment]
@avrham i have added husky pre-commit hook now people wont be able to added further eslint warnings.

**Comment by avrhamNeeman** [comment]
@rolwin100, It's a huge and important PR! Thanks for that.
I will go over it and also check about the Husky package.

**Comment by avrhamNeeman** [comment]
@rolwin100, Sorry for the late response. We have been busy publishing our Cloud.
Please open PR to the ui-warning-fixes branch. It will help us to check and validate the code.

**Comment by rolwin100** [comment]
The pr is still open

**Pull request closed without merging**
